name: build_test_armhf
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build_test_linux:
    name: ${{ matrix.python-version }} on linux-armhf
    runs-on: [self-hosted, ARM]
    strategy:
      fail-fast: false
      matrix:
        python-version: ["python3.9"]

    steps:
    - name: Cleanup build folder
      run: |
        ls -la ./
        rm -rf ./* || true
        rm -rf ./.??* || true
        ls -la ./

    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install requirements
      run: |
        ${{ matrix.python-version }} -m pip install --upgrade pip
        ${{ matrix.python-version }} -m pip install -r requirements.txt

    - name: Build
      run: |
        ${{ matrix.python-version }} -m pip install .

    - name: Test and generate coverage report
      run: |
        python -m pytest tests.py
